### PR TITLE
Add envsubst package

### PR DESCRIPTION
**Pull request by stefanprodan**
This PR contains a fork of https://github.com/gomodules/envsubst and incorporates https://github.com/drone/envsubst/pull/34.

This **permanent fork** is needed because envsubst powers a GA feature of Flux, and the Drone's project looks like is no longer maintained.

xref: https://github.com/fluxcd/flux2/issues/4694

### CODE REVIEW

**Comment by makkes** [comment]
I think we should accompany this PR with an upstream PR to gomodules/envsubst to add the feature of https://github.com/drone/envsubst/pull/34 so that we can remove this fork from our repo once gomodules/envsubst has been released with the feature.

**Comment by stefanprodan** [comment]
@makkes we can't do that, `gomodules/envsubst` has diverged from upstream and requires all vars to be specified.

**Comment by makkes** [comment]
> @makkes we can't do that, `gomodules/envsubst` has diverged from upstream and requires all vars to be specified. Also we may want to add features specific to Flux, for example functions to cope with YAML numbers & booleans.

Ah, I understand. So this is meant to be a permanent fork. 👍🏻

**Review by makkes — APPROVED** [review]

**Review by souleb — APPROVED** [review]
LGTM!

**Pull request merged**
