### PR TITLE
Update dependencies across packages

### PR DESCRIPTION
**Pull request by hiddeco**

### CODE REVIEW

**Review by stefanprodan — APPROVED** [review]
LGTM

**Review by aryan9600 — APPROVED** [review]

**Comment by stefanprodan** [comment]
@aryan9600 looks like BitBucket changed in go-git-providers and the tests here now panic. Can you look into this?

**Comment by aryan9600** [comment]
its panicking because we go-git-providers uses the returned response without checking if its nil: https://github.com/fluxcd/go-git-providers/blob/v0.15.3/stash/repositories.go#L226
i don't know why is there an error in the first place, since there have been no changes to the relevant e2e code. @souleb any ideas?

**Comment by hiddeco** [comment]
Created a fix instead in https://github.com/fluxcd/go-git-providers/pull/223

**Comment by hiddeco** [comment]
Based on the CI failure there the certificate of the testing instance has expired. Given this, and the fact that it's in a testing package, going to merge and ignore the failure for now.

**Pull request merged**
