### PR TITLE
FOSSA scan enabled

### PR DESCRIPTION
**Pull request by idvoretskyi**
Ref.: https://github.com/cncf/foundation/issues/109

Signed-off-by: Ihor Dvoretskyi <ihor@linux.com>

### CODE REVIEW

**Comment by idvoretskyi** [comment]
cc @stefanprodan @dholbach

**Comment by stefanprodan** [comment]
Each directory in this repo is a standalone go package, I think fossa should detect that there are many go.mod files and scan each one?

**Comment by idvoretskyi** [comment]
@stefanprodan ah, I see. No, I assume FOSSA is able to scan code only, so it's irrelevant here.

Thanks for clarifying.

**Comment by stefanprodan** [comment]
All these packages are included in source/kustomize/helm controllers so we scan them there, all good 👍

**Pull request closed without merging**
