### PR TITLE
Upgrade go-git to 5.10.0

### PR DESCRIPTION
**Pull request by makkes**
This will fix https://github.com/fluxcd/source-controller/issues/1239

### CODE REVIEW

**Review by pjbgf — APPROVED** [review]
Nice one following up on this @makkes. :bow:

**Review by stefanprodan — APPROVED** [review]
🎉

**Comment by makkes** [comment]
> With go-git returning proper error for remote errors, do we still need this https://github.com/fluxcd/pkg/blob/git/gogit/v0.14.2/git/gogit/clone.go#L615 anymore?

Yes, as of go-git 5.10.0 the library shouldn't return such errors, anymore, so `goGitError` would never replace anything.

**Comment by makkes** [comment]
Sorry for the confusion. Next try:

As of go-git 5.10.0 the library shouldn't return such errors, anymore, so `goGitError` would never replace anything. For this reason we can remove `goGitError`.

**Pull request merged**
