### PR TITLE
Factor change predicate out of fluxcd/source-controller

### PR DESCRIPTION
**Pull request by squaremo**
Many of the controllers in gitops toolkit follow the pattern of running on an interval, except when there's a specific annotation saying to run ASAP.

The "except" is encapsulted in a predicate, which filters Update events for those in which the generation has changed OR the specific annotation has changed.

---

Possible gotcha here: the name of the annotation is taken from github.com/fluxcd/source-controller/api, which is its own module; if other code refers to this module, it'll drag in controller-runtime, which wouldn't be the case for source-controller/api. If this is a problem, that const can be put in another module.

### CODE REVIEW

**Comment by stefanprodan** [comment]
All API packages are importing `sigs.k8s.io/controller-runtime/pkg/scheme` so I don't see any issues with having the annotation in this package. Can you please run go mod tidy and commit go.sum?

**Comment by stefanprodan** [comment]
I think the logger package could be part of the runtime as well.

**Review by stefanprodan — APPROVED** [review]
LGTM

**Comment by squaremo** [comment]
Follow-up:

 - [ ] change imports of logger
 - [ ] use `ChangePredicate` from controllers and remove any duplicates
 - [ ] use `ReconcileAtAnnotation` from controllers and remove any duplicates

**Comment by stefanprodan** [comment]
Can you please run make release-runtime so we can use a v0.0.1 as the package version in controllers.

**Pull request merged**
