### PR TITLE
Generate deepcopy method for event

### PR DESCRIPTION
**Pull request by SomtochiAma**
Signed-off-by: Somtochi Onyekwere <somtochionyekwere@gmail.com>

### CODE REVIEW

**Review by hiddeco — APPROVED** [review]
Thank you @SomtochiAma :sun_with_face:

**Review by hiddeco — COMMENTED** [review]
The instruction I originally gave you are a bit awkward for this package. To resolve the issue that the CI is giving you, the best option is probably to delete the `runtime/events/doc.go` file, and add the following above the `Event` structure:

```go
// Event is a report of an event issued by a controller.
// +kubebuilder:object:generate=true
type Event struct {
	// The object that this event is about.
```

This should result in the `DeepCopy` methods only being generated for that struct, while others are left alone.

**Review by stefanprodan — APPROVED** [review]
LGTM

Please squash the commits, thanks @SomtochiAma

**Review by hiddeco — APPROVED** [review]
🌈

**Pull request merged**
